global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:8181"]

  # - job_name: "gin_app"
  #   static_configs:
  #     - targets: ["host.docker.internal:8088"]