version: '3'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: myconsul
    networks:
      - kong-net
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/consul/data
    command: "agent -server -ui -node=n1 -bootstrap-expect=1 -client=0.0.0.0"


networks:
  kong-net:
    external: true

volumes:
  consul-data:


