version: '3.8'

services:
  db:
    image: mysql:8.0.13 
    container_name: mysql-latest
    environment:
      MYSQL_ROOT_PASSWORD: sa123456
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf  # 确保缩进正确
    restart: always
    networks:
      - promexus_monitoring

volumes:
  db_data:
    driver: local

networks:
  promexus_monitoring:
    external: true


  # docker run -d \
  # --name mysql-latest \
  # -e MYSQL_ROOT_PASSWORD=sa123456 \
  # -e MYSQL_USER=sa \
  # -e MYSQL_PASSWORD=sa123456 \
  # -e MYSQL_DATABASE=test\
  # -p 3306:3306 \
  # -v db_data:/var/lib/mysql \
  # mysql:latest